### ISSUE TITLE
JWT Middleware

### ISSUE THREAD

**Issue by dwedigital** [howtographql/graphql-python#13]
In your instructions you have the following:

```
GRAPHENE = {
    'SCHEMA': 'hackernews.schema.schema',
    # Add the line below
    'MIDDLEWARE': [
        'graphql_jwt.middleware.JSONWebTokenMiddleware',
    ],
}
```

`'graphql_jwt.middleware.JSONWebTokenMiddleware',` should just go into the Middleware section already in the `settings.py` file - not under the Graphene section

**Comment by F0rge1cE** [comment]
Same issue here: https://github.com/howtographql/howtographql/issues/983

**Comment by mlab817** [comment]
Came across the same issue today so still not fixed.

**Comment by fighcell** [comment]
This issue is still in the tutorial as of 13th June 2020. Following this issue resolution of [issue](https://github.com/howtographql/howtographql/issues/983) by
removing the GRAPHENE variables MIDDLEWARE and adding to the MIDDLEWARE variable fixed the issue.

Check resolution here: [https://github.com/howtographql/howtographql/issues/983](url)

**Comment by Ivo-Evans** [comment]
Another solution in #10

**Comment by pratt3000** [comment]
should be "MIDDLEWARES", that fixed it for me. The "S" is missing in the tutorial as well as the source
